language: node_js
node_js:
  - "8"

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  fqdn: jsoxford.com
  on:
    branch: master
